apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guestbook-ingress
  annotations:
    cert-manager.io/issuer: letsencrypt-guestbook-issuer
spec:
  ingressClassName: traefik
  rules:
  - host: guestbook-tvu.duckdns.org
    http:
      paths:
      # Static files served by nginx
      - path: /static
        pathType: Prefix
        backend:
          service:
            name: nginx-static-service
            port:
              number: 80
      # All other requests go to the main app
      - path: /
        pathType: Prefix
        backend:
          service:
            name: guestbook-service
            port:
              number: 80
  tls:
  - hosts:
    - guestbook-tvu.duckdns.org
    secretName: guestbook-tls-cert
