apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guestbook

resources:
  - guestbook-deployment.yaml
  - guestbook-service.yaml
  - nginx-deployment.yaml
  - nginx-service.yaml
  - nginx-configmap.yaml
  - ingress.yaml
  - cert-issuer.yaml

images:
  - name: guestbook
    newName: ghcr.io/vuillthe/guestbook-gitops
    newTag: main-4cd1f8b
